package com.disaster.session.privacy;

import com.disaster.session.audit.AuditEventType;
import com.disaster.session.audit.AuditService;
import com.disaster.session.model.MfaVerification;
import com.disaster.session.model.User;
import com.disaster.session.model.UserSession;
import com.disaster.session.repository.MfaVerificationRepository;
import com.disaster.session.repository.SessionRepository;
import com.disaster.session.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Builds a copy of the account data this service holds, for GDPR Art. 15 (access) and
 * Art. 20 (portability).
 *
 * <h2>What is deliberately left out</h2>
 *
 * Art. 15(1) gives a person a copy of personal data concerning them. It does not
 * require -- and Art. 32 argues against -- handing back the secrets that protect the
 * account. None of the following is exported:
 *
 * <ul>
 *   <li>{@code passwordHash} -- exporting it turns a subject access request into an
 *       offline cracking target, and the person already knows their own password
 *   <li>{@code mfaSecret} and {@code mfaBackupCodes} -- the whole point of a second
 *       factor is that it is not obtainable through the first
 *   <li>{@code sessionToken} and {@code refreshToken} -- live bearer credentials; an
 *       export file is downloaded, synced and mailed around
 *   <li>{@code verificationCode} on MFA challenges -- same reasoning
 * </ul>
 *
 * <p>The <em>existence</em> and metadata of each of these is exported, because that is
 * the part that is genuinely information about the person: that MFA is enabled, when
 * the password last changed, which devices hold live sessions. Recital 63 makes the
 * same distinction -- the right of access must not adversely affect the rights of
 * others, and it is not a mechanism for extracting credentials.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AccountDataExportService {

    /** Bumped when the export layout changes, so consumers can adapt. */
    private static final String EXPORT_FORMAT_VERSION = "1.0";

    private final UserRepository userRepository;
    private final SessionRepository sessionRepository;
    private final MfaVerificationRepository mfaVerificationRepository;
    private final AuditService auditService;

    /**
     * Assembles everything this service holds about one person.
     *
     * @param username the authenticated principal's name
     * @param sourceAddress caller address, for the audit record
     * @return nested maps that serialise directly to JSON, satisfying the "structured,
     *     commonly used and machine readable" wording of Art. 20(1)
     * @throws IllegalArgumentException if no such account exists
     */
    @Transactional(readOnly = true)
    public Map<String, Object> exportAccountData(String username, String sourceAddress) {
        User user = userRepository.findByUsernameOrEmail(username, username)
                .orElseThrow(() -> new IllegalArgumentException("No account found for the caller"));

        Map<String, Object> export = new LinkedHashMap<>();
        export.put("exportFormatVersion", EXPORT_FORMAT_VERSION);
        export.put("generatedAt", LocalDateTime.now().toString());
        export.put("producedBy", "user-session");
        export.put("subjectIdentifier", user.getId().toString());

        export.put("account", describeAccount(user));
        export.put("securitySettings", describeSecuritySettings(user));
        export.put("sessions", describeSessions(user));
        export.put("multiFactorChallenges", describeMfaChallenges(user));
        export.put("excludedForSecurity", describeExclusions());
        export.put("dataHeldByOtherServices", describeOtherServices());

        // An access request is itself a security-relevant event: it is the step an
        // attacker with a stolen session takes to harvest everything at once (AU-2).
        auditService.recordSuccess(AuditEventType.DATA_EXPORTED, username,
                "/auth/privacy/export", sourceAddress,
                "Subject access export generated by user-session");

        log.info("Account data export generated");
        return export;
    }

    private Map<String, Object> describeAccount(User user) {
        Map<String, Object> account = new LinkedHashMap<>();
        account.put("username", user.getUsername());
        account.put("email", user.getEmail());
        account.put("firstName", user.getFirstName());
        account.put("lastName", user.getLastName());
        account.put("phoneNumber", user.getPhoneNumber());
        account.put("organization", user.getOrganization());
        account.put("role", String.valueOf(user.getRole()));
        account.put("accountType", String.valueOf(user.getAccountType()));
        account.put("isActive", user.getIsActive());
        account.put("isEmailVerified", user.getIsEmailVerified());
        account.put("createdAt", String.valueOf(user.getCreatedAt()));
        account.put("updatedAt", String.valueOf(user.getUpdatedAt()));
        account.put("lastLogin", String.valueOf(user.getLastLogin()));

        Map<String, Object> mbti = new LinkedHashMap<>();
        mbti.put("value", user.getMbtiType());
        // Naming the basis inline answers Art. 15(1)(a) at the point the person is
        // looking at the field, rather than in a policy document elsewhere.
        mbti.put("purpose", "Interface personalisation");
        mbti.put("lawfulBasis", "CONSENT");
        mbti.put("note", "Optional. Withdrawing consent for interface personalisation "
                + "stops this being used and it can be cleared from your profile.");
        account.put("personalityType", mbti);

        return account;
    }

    private Map<String, Object> describeSecuritySettings(User user) {
        Map<String, Object> security = new LinkedHashMap<>();
        security.put("multiFactorEnabled", user.getMfaEnabled());
        security.put("multiFactorMethod", String.valueOf(user.getMfaType()));
        // Whether backup codes exist, not what they are.
        security.put("backupCodesConfigured",
                user.getMfaBackupCodes() != null && user.getMfaBackupCodes().length > 0);
        security.put("passwordLastChangedAt", String.valueOf(user.getPasswordChangedAt()));
        security.put("accountLocked", user.getIsLocked());
        security.put("lockedUntil", String.valueOf(user.getLockedUntil()));
        security.put("failedLoginAttempts", user.getFailedLoginAttempts());

        Map<String, Object> sso = new LinkedHashMap<>();
        sso.put("provider", user.getSsoProvider());
        sso.put("linked", user.getSsoProvider() != null);
        // ssoSubjectId is the identifier at the provider, which is personal data about
        // the person and belongs in their export.
        sso.put("subjectIdAtProvider", user.getSsoSubjectId());
        security.put("singleSignOn", sso);

        return security;
    }

    /**
     * Session history: where and when the account was used.
     *
     * <p>Genuinely useful to a person exercising Art. 15 -- it is how they discover a
     * session they do not recognise -- so the address and user agent are included even
     * though they are personal data. They are the subject's own data.
     */
    private List<Map<String, Object>> describeSessions(User user) {
        List<UserSession> sessions = sessionRepository.findByUserId(user.getId());
        return sessions.stream().map(session -> {
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("ipAddress", session.getIpAddress());
            entry.put("userAgent", session.getUserAgent());
            entry.put("isActive", session.getIsActive());
            entry.put("createdAt", String.valueOf(session.getCreatedAt()));
            entry.put("lastActivity", String.valueOf(session.getLastActivity()));
            entry.put("expiresAt", String.valueOf(session.getExpiresAt()));
            return entry;
        }).toList();
    }

    /** MFA challenge history without the codes themselves. */
    private List<Map<String, Object>> describeMfaChallenges(User user) {
        List<MfaVerification> verifications = mfaVerificationRepository.findByUserId(user.getId());
        return verifications.stream().map(verification -> {
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("method", String.valueOf(verification.getMfaType()));
            entry.put("verified", verification.getIsVerified());
            entry.put("attempts", verification.getAttempts());
            entry.put("createdAt", String.valueOf(verification.getCreatedAt()));
            entry.put("verifiedAt", String.valueOf(verification.getVerifiedAt()));
            return entry;
        }).toList();
    }

    /**
     * States what was withheld and why.
     *
     * <p>Art. 15 is a right to know what is held, so silently omitting fields would
     * misrepresent the export as complete. Listing them by name, with the reason, is
     * both more honest and more useful than leaving the person to guess.
     */
    private List<Map<String, String>> describeExclusions() {
        return List.of(
                Map.of("field", "passwordHash",
                        "reason", "Withheld under Art. 32. Exporting a password hash creates "
                                + "an offline cracking target and tells you nothing you do not know."),
                Map.of("field", "mfaSecret, mfaBackupCodes",
                        "reason", "Withheld under Art. 32. A second factor obtainable through "
                                + "the first is not a second factor."),
                Map.of("field", "sessionToken, refreshToken",
                        "reason", "Withheld under Art. 32. These are live bearer credentials; "
                                + "an export file is downloaded, synced and forwarded."),
                Map.of("field", "MFA verification codes",
                        "reason", "Withheld under Art. 32, same reasoning as the MFA secret."));
    }

    /** Where the rest of the person's data lives, so the export is not mistaken for all of it. */
    private List<Map<String, String>> describeOtherServices() {
        return List.of(
                Map.of("service", "disaster-integrator",
                        "contains", "Health records, location history, consent decisions",
                        "requestVia", "GET /api/integrator/privacy/export"),
                Map.of("service", "collaboration-service",
                        "contains", "Session participation, annotations you authored",
                        "requestVia", "GET /api/collaboration/privacy/export"),
                Map.of("service", "user-session (audit trail)",
                        "contains", "Security events attributed to a pseudonym derived from "
                                + "your account. Retained under Art. 17(3)(b) and NIST AU-11; "
                                + "not included here because it is not keyed by account.",
                        "requestVia", "Contact the controller"));
    }
}
