package com.disaster.integrator.privacy.dsr;

import com.disaster.integrator.model.IndividualHealthData;
import com.disaster.integrator.model.UserLocation;
import com.disaster.integrator.privacy.consent.ConsentRecord;
import com.disaster.integrator.privacy.consent.ConsentService;
import com.disaster.integrator.privacy.consent.ProcessingPurpose;
import com.disaster.integrator.repository.IndividualHealthDataRepository;
import com.disaster.integrator.repository.UserLocationRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Implements the data subject rights this service can satisfy on its own.
 *
 * <p>Covers Art. 15 (access), Art. 17 (erasure) and Art. 20 (portability) over the
 * records held by disaster-integrator. Personal data held by the other services --
 * accounts in user-session, messages in collaboration-service -- is out of this
 * service's reach; {@link #exportAllData} names those explicitly rather than implying
 * the export is complete when it is not.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class DataSubjectRightsService {

    /** Bumped when the export layout changes, so consumers can adapt. */
    private static final String EXPORT_FORMAT_VERSION = "1.0";

    private final IndividualHealthDataRepository healthDataRepository;
    private final UserLocationRepository locationRepository;
    private final ConsentService consentService;
    private final ErasureReceiptRepository erasureReceiptRepository;

    /**
     * Builds a machine-readable copy of everything this service holds about a person.
     *
     * <p>Serves Art. 15 and Art. 20 together: the structure is plain nested maps that
     * serialise to JSON, which satisfies the "structured, commonly used and machine
     * readable" wording of Art. 20(1). Values are decrypted on the way out by the JPA
     * converters, so the export is readable by the person, not only by the platform.
     */
    @Transactional(readOnly = true)
    public Map<String, Object> exportAllData(String userId) {
        Map<String, Object> export = new LinkedHashMap<>();

        export.put("exportFormatVersion", EXPORT_FORMAT_VERSION);
        export.put("generatedAt", LocalDateTime.now().toString());
        export.put("subjectIdentifier", userId);
        export.put("producedBy", "disaster-integrator");

        export.put("healthData", healthDataRepository.findByUserId(userId)
                .map(this::describeHealthData)
                .orElse(null));

        export.put("locations", locationRepository.findByUserId(userId).stream()
                .map(this::describeLocation)
                .toList());

        export.put("consentHistory", consentService.history(userId).stream()
                .map(this::describeConsent)
                .toList());

        export.put("currentConsents", describeCurrentConsents(userId));

        // Naming the gaps is part of the obligation, not a caveat around it: an export
        // that silently omits a system leaves the person unable to exercise Art. 15
        // against that system.
        export.put("dataHeldByOtherServices", List.of(
                Map.of("service", "user-session",
                        "contains", "Account profile, credentials, sessions, MFA enrolment",
                        "requestVia", "GET /api/auth/privacy/export"),
                Map.of("service", "collaboration-service",
                        "contains", "Messages and room membership you have authored",
                        "requestVia", "GET /api/collaboration/privacy/export")));

        log.info("Data subject access export generated by disaster-integrator");
        return export;
    }

    /**
     * Erases the personal data this service holds and records that it happened.
     *
     * <p>The consent trail is deliberately kept. Art. 17(3)(b) permits retention where
     * it is needed to establish or defend legal claims, and destroying the evidence of
     * what a person agreed to would leave the controller unable to demonstrate its
     * lawful basis under Art. 7(1). What survives is only the identifier, purpose,
     * decision and timestamp.
     *
     * @return a receipt describing what was removed and what was kept
     */
    @Transactional
    public ErasureReceipt eraseAllData(String userId, String requestedVia) {
        List<String> categoriesErased = new ArrayList<>();

        if (healthDataRepository.existsByUserId(userId)) {
            healthDataRepository.deleteByUserId(userId);
            categoriesErased.add("HEALTH_RECORDS");
        }

        List<UserLocation> locations = locationRepository.findByUserId(userId);
        if (!locations.isEmpty()) {
            locationRepository.deleteAll(locations);
            categoriesErased.add("LOCATION_HISTORY");
        }

        ErasureReceipt receipt = ErasureReceipt.builder()
                .userId(userId)
                .categoriesErased(String.join(",", categoriesErased))
                .categoriesRetained("CONSENT_AUDIT_TRAIL")
                .retentionJustification(
                        "Consent decisions retained under Art. 17(3)(b) so the controller can "
                        + "continue to demonstrate the lawful basis relied on, as Art. 7(1) requires.")
                .requestedVia(requestedVia)
                .erasedAt(LocalDateTime.now())
                .build();

        ErasureReceipt saved = erasureReceiptRepository.save(receipt);
        log.info("Erasure completed across {} data categories", categoriesErased.size());
        return saved;
    }

    /** Every purpose with its current state, description and lawful basis. */
    private List<Map<String, Object>> describeCurrentConsents(String userId) {
        List<Map<String, Object>> purposes = new ArrayList<>();
        Map<ProcessingPurpose, Boolean> current = consentService.currentConsents(userId);
        current.forEach((purpose, granted) -> {
            Map<String, Object> entry = new LinkedHashMap<>();
            entry.put("purpose", purpose.name());
            entry.put("displayName", purpose.getDisplayName());
            entry.put("description", purpose.getDescription());
            entry.put("lawfulBasis", purpose.getLawfulBasis().name());
            entry.put("involvesSpecialCategoryData", purpose.involvesSpecialCategoryData());
            entry.put("currentlyGranted", granted);
            purposes.add(entry);
        });
        return purposes;
    }

    private Map<String, Object> describeConsent(ConsentRecord record) {
        Map<String, Object> entry = new LinkedHashMap<>();
        entry.put("purpose", record.getPurpose().name());
        entry.put("decision", record.getDecision().name());
        entry.put("lawfulBasis", record.getLawfulBasis().name());
        entry.put("textYouWereShown", record.getPresentedText());
        entry.put("capturedVia", record.getCapturedVia());
        entry.put("recordedAt", String.valueOf(record.getRecordedAt()));
        return entry;
    }

    private Map<String, Object> describeLocation(UserLocation location) {
        Map<String, Object> entry = new LinkedHashMap<>();
        entry.put("label", location.getLabel());
        entry.put("locationType", location.getLocationType());
        entry.put("latitude", location.getLatitude());
        entry.put("longitude", location.getLongitude());
        entry.put("address", location.getAddress());
        entry.put("city", location.getCity());
        entry.put("state", location.getState());
        entry.put("zipCode", location.getZipCode());
        entry.put("country", location.getCountry());
        entry.put("isPrimary", location.getIsPrimary());
        entry.put("shareLocation", location.getShareLocation());
        entry.put("sharingLevel", location.getSharingLevel());
        entry.put("recordedAt", String.valueOf(location.getTimestamp()));
        return entry;
    }

    private Map<String, Object> describeHealthData(IndividualHealthData data) {
        Map<String, Object> entry = new LinkedHashMap<>();
        entry.put("source", data.getSource());
        entry.put("firstName", data.getFirstName());
        entry.put("lastName", data.getLastName());
        entry.put("dateOfBirth", String.valueOf(data.getDateOfBirth()));
        entry.put("gender", data.getGender());
        entry.put("bloodType", data.getBloodType());
        entry.put("phoneNumber", data.getPhoneNumber());
        entry.put("email", data.getEmail());
        entry.put("medicalConditions", data.getMedicalConditions());
        entry.put("allergies", data.getAllergies());
        entry.put("medications", data.getMedications());
        entry.put("immunizations", data.getImmunizations());
        entry.put("requiresMobilityAssistance", data.getRequiresMobilityAssistance());
        entry.put("requiresOxygen", data.getRequiresOxygen());
        entry.put("requiresDialysis", data.getRequiresDialysis());
        entry.put("requiresElectricity", data.getRequiresElectricity());
        entry.put("specialNeeds", data.getSpecialNeeds());
        entry.put("emergencyContacts", data.getEmergencyContacts());
        entry.put("primaryPhysician", data.getPrimaryPhysician());
        entry.put("physicianPhone", data.getPhysicianPhone());
        entry.put("preferredHospital", data.getPreferredHospital());
        entry.put("insuranceProvider", data.getInsuranceProvider());
        entry.put("insurancePolicyNumber", data.getInsurancePolicyNumber());
        entry.put("riskLevel", data.getRiskLevel());
        entry.put("riskFactors", data.getRiskFactors());
        entry.put("createdAt", String.valueOf(data.getCreatedAt()));
        entry.put("updatedAt", String.valueOf(data.getUpdatedAt()));
        return entry;
    }
}
